# Generated by Django 2.0.7 on 2018-07-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('kind', models.CharField(max_length=10)),
                ('sale', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='dish_pic/')),
            ],
        ),
    ]
