# Generated by Django 2.0.7 on 2018-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_bill_dishcomment_servercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='dish_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
