# Generated by Django 2.0.7 on 2018-07-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20180724_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='dish_id',
            field=models.IntegerField(default=0),
        ),
    ]
